[tool.poetry]
name = "injecty"
version = "0.0.0"  # Placeholder - actual version will be determined from git tags
description = "A simple IOC / Dependency injection micro framework for Python."
authors = ["Tim O'Farrell <tofarr@gmail.com>"]
readme = "README.md"
packages = [{include = "injecty"}]
exclude = ["tests*", "examples"]
repository = "https://github.com/tofarr/servey-stub"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"  # Setting a reasonable Python version requirement

[tool.poetry.group.dev.dependencies]
black = "~23.3"
pytest = "~7.2"
pytest-cov = "~4.0"
pytest-xdist = "~3.2"
pylint = "~3.0"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0"]
build-backend = "poetry.dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
pattern = "^(?P<base>\\d+\\.\\d+\\.\\d+)$"
